import mongoose from 'mongoose';

const Schema = mongoose.Schema;

const userSchema = new Schema({
    userName: {
        type: String,
        required: true, 
        unique: false, 
        trim: true, 
        minlength: 3 
    },
    email: {
        type: String, 
        required: true,
    }, 
    password: {
        type: String,
        required: true,
    },
});

/**
 * Captures the friends of a user
 * userId, friendId and frendRequestId is auto-generated by mongoDb
 */
const friendshipSchema = new Schema({
    userId: {
        type: String,
        required: true,
        unique: true,
    },
    friendsId: {
        type: Array,
    }, 
    friendRequestId: {
        type: Array,
    }
});

// collection = 'User' 
// base it on userSchema
const User = mongoose.model('User', userSchema);

export default User;